name       : libticables
version    : 1.3.5
release    : 1
source     :
    - https://downloads.sourceforge.net/project/tilp/tilp2-linux/tilp2-1.18/libticables2-1.3.5.tar.bz2 : 0c6fb6516e72ccab081ddb3aecceff694ed93aec689ddd2edba9c7c7406c4522
license    : GPL-2.0-or-later
component  : programming.library
summary    : TiLP link cable library
description: |
    This library is part of the TiLP project.
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %reconfigure --enable-libusb10
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/69-libticables.rules $installdir/usr/lib/udev/rules.d/69-libticables.rules
